package main

import (
	"fmt"
)

func main(){
	fmt.Println(string(findTheDifference2("abcd","abcde")))
}

/**
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
*/
func findTheDifference(s string, t string) byte {
	//character in map that contains odd number
	diff := make(map[byte]int)
	for i := 0; i < len(s); i++ {
		if _,ok := diff[s[i]]; !ok {
			diff[s[i]] = 1
		} else {
			diff[s[i]]++
		}
	}

	for i := 0; i < len(t); i++ {
		if _,ok := diff[t[i]]; !ok {
			diff[t[i]] = 1
		} else {
			diff[t[i]]++
		}
	}
	added := ""
	for c,v := range diff {
		if v % 2 != 0 {
			added = string(c)
			break
		}
	}
	result := []byte(added)
	return result[0]
}

func findTheDifference2(s string, t string) byte {
	// a XOR a = 0; a XOR 0 = a; a XOR b XOR a = b
	diff := byte(0)
	for i := 0; i < len(s); i++ {
		diff = diff ^ s[i]
	}

	for i := 0; i < len(t); i++ {
		diff = diff ^ t[i]
	}
	return diff
}